server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://kqsfduhavrmvky:8ef27aa169518d8a820c6b6b569808678ff6ca158386483c5c87b0271adbc645@ec2-184-73-198-174.compute-1.amazonaws.com:5432/d9hcsj2nrfl47t
    username: kqsfduhavrmvky
    password: 8ef27aa169518d8a820c6b6b569808678ff6ca158386483c5c87b0271adbc645
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Satander
